name: ci

on:
  push:
    branches: [main]

jobs:
  # 1. Job: Native x86
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}
      - name: Build and push x86
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/mattipunkt/cms:amd64 # Eigener Tag!

  # 2. Job: Native ARM (dein ubuntu-24.04-arm)
  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}
      - name: Build and push ARM
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: ghcr.io/mattipunkt/cms:arm64 # Eigener Tag!

  # 3. Job: Das Manifest erstellen (Der "Kleber")
  create-manifest:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64] # Wartet auf beide
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}
          
      - name: Create and push manifest
        run: |
          # Erstellt eine Liste, die beide Einzel-Images unter :latest vereint
          docker buildx imagetools create -t ghcr.io/mattipunkt/cms:latest \
            ghcr.io/mattipunkt/cms:amd64 \
            ghcr.io/mattipunkt/cms:arm64
